### ISSUE TITLE
How we can send a request to other methods in a custom app or in Erpnext?

### ISSUE THREAD

**Issue by yrestom** [leam-tech/renovation-core#45]
How we can send a request to other methods in a custom app or in Erpnext?

Like when we use `frappe.call` to send a request to python function at the backend

Thanks

**Comment by nabilshuja** [comment]
You should be able to make a request using `renovation.call` here's an example of the usage;

```ts
const r = await renovation.call({
  cmd: 'frappe.core.doctype.file.file.get_files_in_folder',
  folder: 'Home',
});
```
this will reference method [here](https://github.com/frappe/frappe/blob/a9411e845634174a7f8c8b11aa0f3dbdbaa4ac7c/frappe/core/doctype/file/file.py#L963).

notice the location of the method against the file location `frappe/core/doctype/file/file.py`. 

So, similarly you'll be able to make a request using `[App Name/Erpnext].[file location].[Method Name]`

**Comment by yrestom** [comment]
Thank you

And how we can passing the data or the parameters

Please can you give an example 

Thanks

**Comment by nabilshuja** [comment]
>And how we can passing the data or the parameters

Using the example shown above;

So, the parameter by this [method](https://github.com/frappe/frappe/blob/a9411e845634174a7f8c8b11aa0f3dbdbaa4ac7c/frappe/core/doctype/file/file.py#L963) can accept `folder`, `start`, `page_length`.

We can include it similarly within `renovation.call`, notice the similar keys as part of the request body;

```ts
const r = await renovation.call({
  cmd: 'frappe.core.doctype.file.file.get_files_in_folder',
  folder: 'Home',
  start: 20,
  page_length: 20,
});
```

**Comment by yrestom** [comment]
Thank you
