### ISSUE TITLE
Process is not defined in TestManager

### ISSUE THREAD

**Issue by nabilshuja** [leam-tech/renovation-core#9]
On fresh Install of renovation-core in Angular, the following error shows up when running the application.

<img width="870" alt="Screen Shot 2020-04-19 at 12 01 16 PM" src="https://user-images.githubusercontent.com/25796380/79682911-49ba9c00-8237-11ea-94a7-bc552237d935.png">

From here, in the class TestManager
```
public static getVariables(variableName: ENV_VARIABLES): string {
    return process.env[variableName];
  }
```

This does not seem to be the case when doing it elsewhere.

**Comment by assemmarwan** [comment]
Please elaborate more on the "case when doing it elsewhere".

**Comment by nabilshuja** [comment]
In the case of running it on a Nuxt application, the error is not thrown.

**Comment by assemmarwan** [comment]
Alright I reckon I know what the issue is. `process` isn't available in the browser and since class properties are initialized using `getVariables()`, it fails.

Will make a PR soon.

**Comment by assemmarwan** [comment]
Check #11
